services:
  - type: web
    name: next-js-app
    env: node
    plan: free
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm start'
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
